name: WDP-Help
version: ${project.version}
main: com.wdp.help.WDPHelpPlugin
api-version: '1.21'
description: AI-Powered Help System for WDP Server
author: WDP Development Team
website: https://wdpserver.com

commands:
  help:
    description: AI-powered help system - ask any question!
    usage: /<command> [question]
    aliases: [wdphelp, askhelp, serverhelp]

permissions:
  wdphelp.use:
    description: Allows using the help command
    default: true
  wdphelp.admin:
    description: Admin permissions for WDP-Help
    default: op
  wdphelp.admin.reload:
    description: Allows reloading the plugin configuration
    default: op
  wdphelp.admin.debug:
    description: Allows viewing debug information
    default: op
